import Link from 'next/link'
import { redirect } from 'next/navigation'
import { supabaseServer } from '@/lib/supabase/clients'

export const dynamic = 'force-dynamic'

export default async function AccountPage() {
  const supabase = await supabaseServer()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login?next=/account')
  const { data: profile } = await supabase.from('profiles').select('full_name, role, phone').eq('id', user.id).single()
  const { count: orderCount } = await supabase.from('orders').select('id', { count: 'exact', head: true }).eq('buyer_id', user.id)
  return <div className="min-h-[calc(100vh-160px)] bg-[#f7f8f6] py-8 sm:py-12"><div className="page-wrap max-w-5xl"><div className="relative overflow-hidden rounded-3xl bg-[#14251e] p-6 text-white sm:p-9"><div className="absolute -right-12 -top-16 h-52 w-52 rounded-full bg-[#d9f33f]/15 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><span className="eyebrow bg-white/10 text-[#d9f33f]">My account</span><h1 className="mt-5 text-3xl font-black tracking-[-.05em] sm:text-5xl">Hello, {profile?.full_name || 'shopper'}.</h1><p className="mt-3 text-sm text-white/65">Your orders, saved details and marketplace activity in one place.</p></div><Link href="/search" className="rounded-xl bg-[#d9f33f] px-4 py-3 text-sm font-black text-[#14251e] hover:bg-white">Continue shopping →</Link></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Link href="/orders" className="surface group p-5 transition hover:-translate-y-1 hover:border-[#14805d]"><span className="text-3xl">📦</span><h2 className="mt-4 text-lg font-black">My orders</h2><p className="mt-1 text-sm text-slate-500">{orderCount ?? 0} order{orderCount === 1 ? '' : 's'} to track and manage.</p><p className="mt-4 text-sm font-bold text-[#14805d]">View orders →</p></Link><Link href="/account/addresses" className="surface group p-5 transition hover:-translate-y-1 hover:border-[#14805d]"><span className="text-3xl">📍</span><h2 className="mt-4 text-lg font-black">Addresses</h2><p className="mt-1 text-sm text-slate-500">Keep delivery details ready for checkout.</p><p className="mt-4 text-sm font-bold text-[#14805d]">Manage addresses →</p></Link><Link href="/sell" className="surface group p-5 transition hover:-translate-y-1 hover:border-[#14805d]"><span className="text-3xl">🏪</span><h2 className="mt-4 text-lg font-black">Start selling</h2><p className="mt-1 text-sm text-slate-500">Turn products you love into a storefront.</p><p className="mt-4 text-sm font-bold text-[#14805d]">Apply to sell →</p></Link></div><div className="surface mt-5 p-5 sm:p-6"><p className="section-kicker">Profile details</p><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Name</p><p className="mt-1 text-sm font-bold">{profile?.full_name || 'Not set'}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Email</p><p className="mt-1 break-all text-sm font-bold">{user.email}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Account type</p><p className="mt-1 text-sm font-bold capitalize">{profile?.role || 'buyer'}</p></div></div></div></div></div>
}
