import { redirect } from 'next/navigation'
import Link from 'next/link'
import { supabaseServer, supabaseAdmin } from '@/lib/supabase/clients'
import RiderActions from '@/components/RiderActions'
import RiderOfferActions from '@/components/RiderOfferActions'
import OrderStatusBadge from '@/components/OrderStatusBadge'

export const dynamic = 'force-dynamic'

function first(value: any) { return Array.isArray(value) ? value[0] : value }
function money(kobo: number | null | undefined) { return `₦${Math.round(Number(kobo || 0) / 100).toLocaleString()}` }

export default async function RiderPage() {
  const supabase = await supabaseServer()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login?next=/rider')
  const db = supabaseAdmin()
  const { data: rider } = await db.from('rider_profiles').select('id, phone, vehicle_type, vehicle_plate, status').eq('user_id', user.id).single()
  if (!rider) redirect('/rider/register')
  if (rider.status !== 'approved') return <main className="page-wrap py-12"><div className="surface mx-auto max-w-xl p-7"><p className="eyebrow">Rider application</p><h1 className="mt-4 text-3xl font-black">Your application is under review</h1><p className="mt-3 text-slate-600">Jojokev will approve your rider account before you can receive delivery assignments.</p></div></main>

  const [{ data: wallet }, { data: offers }, { data: assignments }] = await Promise.all([
    db.from('rider_wallets').select('held_balance_kobo, available_balance_kobo, lifetime_earned_kobo').eq('rider_id', rider.id).maybeSingle(),
    db.from('delivery_offers').select('id, order_id, quote_kobo, status, expires_at, created_at, orders(order_number, addresses(city, state), delivery_areas(name, city, state), order_items(seller_id, seller_profiles(store_area_id, store_areas(name, city, state))))').eq('rider_id', rider.id).eq('status', 'offered').gt('expires_at', new Date().toISOString()).order('created_at', { ascending: false }),
    db.from('delivery_assignments').select('id, order_id, status, assigned_at, rider_quote_kobo, orders(order_number, total_kobo, buyer_id, addresses(full_name, phone, street, city, state, landmark), order_items(product_title, quantity, seller_id, seller_profiles(business_name, business_address, business_phone, store_areas(name, city, state))))').eq('rider_id', rider.id).in('status', ['assigned', 'picked_up', 'out_for_delivery', 'arrived', 'delivered']).order('assigned_at', { ascending: false }),
  ])

  const allAssignments = assignments || []
  const activeAssignments = allAssignments.filter((assignment: any) => assignment.status !== 'delivered')
  const completedAssignments = allAssignments.filter((assignment: any) => assignment.status === 'delivered')

  return <main className="min-h-[calc(100vh-120px)] bg-[#f7f8f6] py-6 sm:py-10"><div className="page-wrap max-w-5xl">
    <section className="rounded-3xl bg-[#14251e] p-6 text-white shadow-md sm:p-9"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="eyebrow bg-white/10 text-[#d9f33f]">Rider workspace</span><h1 className="mt-4 text-3xl font-black tracking-[-.04em]">Wallet & delivery control</h1><p className="mt-2 max-w-xl text-sm text-white/65">Your earnings stay held until the buyer’s private delivery code confirms a completed handover.</p></div><Link href="/notifications" className="rounded-xl bg-[#d9f33f] px-4 py-3 text-center text-sm font-black text-[#14251e]">Open notifications</Link></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-white/60">Available balance</p><p className="mt-2 text-2xl font-black text-[#d9f33f]">{money(wallet?.available_balance_kobo)}</p><Link href="/rider/wallet" className="mt-2 inline-block text-xs font-bold text-white/75 underline">Withdraw funds</Link></div><div className="rounded-2xl border border-amber-200/20 bg-amber-300/10 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-amber-100/75">Held balance</p><p className="mt-2 text-2xl font-black text-amber-100">{money(wallet?.held_balance_kobo)}</p><p className="mt-2 text-xs text-white/60">Released after OTP confirmation</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-white/60">Lifetime earned</p><p className="mt-2 text-2xl font-black">{money(wallet?.lifetime_earned_kobo)}</p><p className="mt-2 text-xs text-white/60">All completed rider earnings</p></div></div></section>

    <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Link href="#quotes" className="surface p-4 transition hover:-translate-y-0.5 hover:border-[#14805d]"><p className="text-2xl font-black text-[#14805d]">{offers?.length || 0}</p><p className="mt-1 text-xs font-bold text-slate-600">Quotes</p></Link><Link href="#live-orders" className="surface p-4 transition hover:-translate-y-0.5 hover:border-[#14805d]"><p className="text-2xl font-black text-[#14805d]">{activeAssignments.length}</p><p className="mt-1 text-xs font-bold text-slate-600">Live orders</p></Link><Link href="#completed" className="surface p-4 transition hover:-translate-y-0.5 hover:border-[#14805d]"><p className="text-2xl font-black text-[#14805d]">{completedAssignments.length}</p><p className="mt-1 text-xs font-bold text-slate-600">Completed</p></Link><Link href="/rider/wallet" className="surface p-4 transition hover:-translate-y-0.5 hover:border-[#14805d]"><p className="text-2xl font-black text-[#14805d]">₦</p><p className="mt-1 text-xs font-bold text-slate-600">Wallet</p></Link><Link href="/notifications" className="surface p-4 transition hover:-translate-y-0.5 hover:border-[#14805d]"><p className="text-2xl font-black text-[#14805d]">•</p><p className="mt-1 text-xs font-bold text-slate-600">Notifications</p></Link></section>

    <section className="surface mt-5 border-amber-200 bg-amber-50 p-5"><p className="section-kicker text-amber-700">Buyer-code safety</p><p className="mt-2 text-sm font-semibold text-amber-800">The delivery code is private to the buyer. It is sent to the buyer’s Jojokev notifications when you mark the order out for delivery. Never ask for it before you are physically with the buyer.</p></section>

    <section id="quotes" className="mt-8 scroll-mt-28"><div className="mb-4 flex items-end justify-between"><div><p className="section-kicker">New work</p><h2 className="section-title">Available quotes</h2></div><p className="text-xs font-semibold text-slate-500">Area details only until acceptance</p></div><div className="space-y-4">{offers?.map((offer: any) => <RiderOfferActions key={offer.id} offer={offer} />)}{!offers?.length && <div className="surface p-8 text-center text-slate-500">No open quotes right now.</div>}</div></section>

    <section id="live-orders" className="mt-10 scroll-mt-28"><div className="mb-4"><p className="section-kicker">Active work</p><h2 className="section-title">Live orders</h2></div><div className="space-y-4">{activeAssignments.map((assignment: any) => { const order = assignment.orders; const address = first(order?.addresses); const items = order?.order_items || []; const sellers = Array.from(new Map(items.map((item: any) => { const seller = first(item.seller_profiles); return [seller?.business_name || item.seller_id, seller] })).values()).filter(Boolean) as any[]; return <article key={assignment.id} className="surface border-2 border-slate-200 p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">{order?.order_number}</p><h2 className="mt-2 text-xl font-black">Active delivery</h2><p className="mt-1 text-sm font-semibold text-[#14805d]">Rider earning: {money(assignment.rider_quote_kobo)}</p><p className="mt-3 text-xs text-slate-500">{items.map((item: any) => `${item.quantity} × ${item.product_title}`).join(' · ')}</p></div><OrderStatusBadge status={assignment.status === 'out_for_delivery' || assignment.status === 'arrived' ? 'shipped' : 'paid'} /></div><div className="mt-5 grid gap-4 border-t border-slate-100 pt-4 md:grid-cols-2"><div className="rounded-2xl bg-[#f7f8f6] p-4"><p className="section-kicker">Pickup details</p>{sellers.length ? sellers.map((seller: any, index: number) => <div key={`${seller.business_name}-${index}`} className={index ? 'mt-4 border-t border-slate-200 pt-4' : 'mt-2'}><p className="font-black">{seller.business_name || 'Seller'}</p><p className="mt-1 text-sm text-slate-700">{seller.business_address}</p><p className="mt-1 text-sm text-slate-700">Phone: {seller.business_phone}</p></div>) : <p className="mt-2 text-sm text-slate-600">Seller pickup details unavailable.</p>}</div><div className="rounded-2xl bg-[#f7f8f6] p-4"><p className="section-kicker">Delivery details</p><p className="mt-2 font-black">{address?.full_name || 'Buyer'}</p><p className="mt-1 text-sm text-slate-700">{address?.street}, {address?.city}, {address?.state}{address?.landmark ? ` · ${address.landmark}` : ''}</p><p className="mt-1 text-sm text-slate-700">Phone: {address?.phone}</p></div></div><div className="mt-5 rounded-2xl border-2 border-[#14805d]/20 bg-[#f7fffb] p-4"><p className="mb-3 text-xs font-extrabold uppercase tracking-[.16em] text-[#0b5d43]">Required next action</p><RiderActions orderId={assignment.order_id} status={assignment.status} /></div></article> })}{!activeAssignments.length && <div className="surface p-8 text-center text-slate-500">No live deliveries. Accept an available quote to begin.</div>}</div></section>

    <section id="completed" className="mt-10 scroll-mt-28"><div className="mb-4"><p className="section-kicker">History</p><h2 className="section-title">Completed deliveries</h2></div>{completedAssignments.length ? <div className="surface divide-y">{completedAssignments.map((assignment: any) => <div key={assignment.id} className="flex flex-col justify-between gap-2 px-5 py-4 sm:flex-row sm:items-center"><div><p className="font-black">{assignment.orders?.order_number || 'Delivery'}</p><p className="text-xs text-slate-500">Completed {assignment.assigned_at ? new Date(assignment.assigned_at).toLocaleDateString() : ''}</p></div><div className="flex items-center gap-3"><span className="font-black text-[#14805d]">{money(assignment.rider_quote_kobo)}</span><span className="rounded-full bg-[#e5f6ee] px-2.5 py-1 text-[10px] font-bold uppercase text-[#0b5d43]">Completed</span></div></div>)}</div> : <div className="surface p-8 text-center text-slate-500">Completed deliveries will appear here.</div>}</section>
  </div></main>
}
