'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { broadcastDeliveryOffer } from '@/app/actions/dispatch'
import OrderStatusBadge from '@/components/OrderStatusBadge'
import { formatNaira } from '@/lib/money'

export default function AdminDispatch({ orders }: { orders: any[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState('')
  async function broadcast(orderId: string) { setBusy(orderId); setMessage(''); const result = await broadcastDeliveryOffer(orderId); setMessage(result.error || result.success || ''); setBusy(null); router.refresh() }
  return <div className="space-y-5"><div className="rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-900">The buyer pays the area delivery fee at checkout. Jojokev sends the internal rider quote to eligible approved riders. Riders accept or decline; never ask the buyer for an extra delivery payment at the door.</div>{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{message}</p>}<div className="space-y-3">{!orders.length ? <div className="surface p-10 text-center text-slate-500">No paid orders are waiting for dispatch.</div> : orders.map((o: any) => { const assignment = o.delivery_assignments?.[0]; const area = Array.isArray(o.delivery_areas) ? o.delivery_areas[0] : o.delivery_areas; const address = Array.isArray(o.addresses) ? o.addresses[0] : o.addresses; const isAssigned = assignment && assignment.status !== 'cancelled'; return <article key={o.id} className="surface p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">{o.order_number}</p><h2 className="mt-2 text-lg font-black">{o.profiles?.full_name || 'Buyer'}</h2><p className="mt-1 text-sm text-slate-500">{formatNaira(o.total_kobo)} · {new Date(o.created_at).toLocaleString('en-NG')}</p></div><OrderStatusBadge status={o.status} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Delivery area</p><p className="mt-1 text-sm font-black text-slate-900">{area?.name || 'Not selected'}</p><p className="text-xs text-slate-500">{area ? `${area.city}, ${area.state}` : address?.city || 'Review address'}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Customer fee</p><p className="mt-1 text-sm font-black text-slate-900">{formatNaira(o.delivery_fee_kobo || area?.customer_fee_kobo || 0)}</p></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-amber-700">Rider quote</p><p className="mt-1 text-sm font-black text-slate-900">{formatNaira(o.rider_quote_kobo || area?.rider_quote_kobo || 0)}</p></div></div><div className="mt-4">{isAssigned ? <div className="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Rider assignment active · {assignment.status.replaceAll('_', ' ')}</div> : <button disabled={busy === o.id} onClick={() => broadcast(o.id)} className="w-full rounded-xl bg-[#16845f] px-4 py-3.5 text-sm font-black text-white hover:bg-[#0f6e4e] disabled:opacity-50">{busy === o.id ? 'Sending quote to eligible riders…' : 'Send quote to all eligible riders'}</button>}</div></article>})}</div></div>
}
