'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { approveSeller, rejectSeller, suspendSeller } from '@/app/actions/admin'

const STATUS_STYLES: Record<string, string> = { pending: 'bg-[#fff7d9] text-[#8d6500]', approved: 'bg-[#e5f6ee] text-[#0b5d43]', rejected: 'bg-red-50 text-red-700', suspended: 'bg-slate-100 text-slate-600' }

export default function AdminSellers({ sellers }: { sellers: any[] }) {
  const [message, setMessage] = useState<{ error?: string; success?: string }>({})
  const [busyId, setBusyId] = useState<string | null>(null)
  const router = useRouter()
  async function act(id: string, fn: () => Promise<any>) { setBusyId(id); setMessage(await fn()); setBusyId(null); router.refresh() }
  if (sellers.length === 0) return <div className="surface p-12 text-center"><div className="text-5xl">♙</div><h2 className="mt-4 text-lg font-black">No seller applications yet</h2><p className="mt-2 text-sm text-slate-500">New applications will appear here for review.</p></div>
  return <div className="space-y-4">{message.error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{message.error}</div>}{message.success && <div className="rounded-xl border border-emerald-200 bg-[#e5f6ee] px-4 py-3 text-sm font-semibold text-[#0b5d43]">{message.success}</div>}{sellers.map(s => <section key={s.id} className="surface p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#e5f6ee] text-xl text-[#0b5d43]">{s.business_name?.slice(0, 1).toUpperCase() || 'S'}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{s.business_name}</h2><span className={`status-pill ${STATUS_STYLES[s.status] || STATUS_STYLES.pending}`}>{s.status}</span></div><p className="mt-1 text-sm text-slate-500">{s.profiles?.full_name || 'Applicant'} · {s.business_phone || 'No phone provided'}</p><p className="mt-2 text-xs text-slate-500">{s.business_address || 'No business address provided'}</p><p className="mt-2 text-[11px] font-semibold text-slate-400">Applied {new Date(s.created_at).toLocaleString('en-NG')}</p></div></div>{s.account_number && <div className="rounded-xl bg-[#f7f8f6] p-3 text-xs text-slate-500 sm:min-w-[210px]"><p className="font-extrabold uppercase tracking-wide text-slate-400">Payout account</p><p className="mt-2 font-bold text-slate-700">{s.bank_name}</p><p className="mt-1">{s.account_number} · {s.account_name}</p></div>}</div><div className="mt-5 flex flex-wrap gap-2 border-t pt-4" style={{ borderColor: 'var(--line)' }}>{s.status === 'pending' && <><button type="button" disabled={busyId === s.id} onClick={() => act(s.id, () => approveSeller(s.id))} className="btn-primary px-4 py-2.5 disabled:opacity-50">Approve seller</button><button type="button" disabled={busyId === s.id} onClick={() => { const reason = window.prompt('Reason for rejection?') ?? ''; if (reason) act(s.id, () => rejectSeller(s.id, reason)) }} className="btn-secondary px-4 py-2.5 text-red-700 hover:border-red-300">Reject</button></>}{s.status === 'approved' && <button type="button" disabled={busyId === s.id} onClick={() => { const reason = window.prompt('Reason for suspension?') ?? ''; if (reason) act(s.id, () => suspendSeller(s.id, reason)) }} className="btn-dark px-4 py-2.5 disabled:opacity-50">Suspend seller</button>}{(s.status === 'rejected' || s.status === 'suspended') && <button type="button" disabled={busyId === s.id} onClick={() => act(s.id, () => approveSeller(s.id))} className="btn-primary px-4 py-2.5 disabled:opacity-50">Re-approve seller</button>}</div></section>)}</div>
}
